### ISSUE TITLE
Kfctl implements new semantics tracking

### ISSUE THREAD

**Issue by gabrielwen** [kubeflow/kfctl#19] opened 2019-09-04 23:27 UTC
- [ ] Add a new flag `-f` #20 
- [ ] `-f` takes both local and remote files #21
- [ ] Implements `build` #22
- [ ] Implements `apply` #23

**Comment by jlewi** [comment] 2019-11-04 23:23
@gabrielwen Can we close this? I think this is implemented in v0.7.0?

Duplicate of kubeflow/kubeflow#3518 ?

**Closed** 2019-11-04 23:53 UTC
Labels: area/1.0.0, area/kfctl, kind/feature, priority/p1
