### ISSUE TITLE
open /opt/my-kubeflow/.cache/manifests/manifests-1.1-branch/stacks/kubernetes/application/spark-operator: no such file or directory  filename="kustomize/kustomize.go:155"

### ISSUE THREAD

**Issue by zhangchunsheng** [kubeflow/kfctl#403] opened 2020-08-31 16:47 UTC
kfctl apply -V -f kfctl_k8s_istio.v1.1.0.yaml

```
INFO[0160] Deploying application spark-operator          filename="kustomize/kustomize.go:248"
2020/09/01 00:42:47 absolute path error in '/opt/my-kubeflow/.cache/manifests/manifests-1.1-branch/stacks/kubernetes/application/spark-operator' : evalsymlink failure on '/opt/my-kubeflow/.cache/manifests/manifests-1.1-branch/stacks/kubernetes/application/spark-operator' : lstat /opt/my-kubeflow/.cache/manifests/manifests-1.1-branch/stacks/kubernetes/application/spark-operator: no such file or directory
ERRO[0160] Error evaluating kustomization manifest for spark-operator: accumulating resources: accumulating resources from '../../.cache/manifests/manifests-1.1-branch/stacks/kubernetes/application/spark-operator': open /opt/my-kubeflow/.cache/manifests/manifests-1.1-branch/stacks/kubernetes/application/spark-operator: no such file or directory  filename="kustomize/kustomize.go:155"
Error: failed to apply:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: error evaluating kustomization manifest for spark-operator: accumulating resources: accumulating resources from '../../.cache/manifests/manifests-1.1-branch/stacks/kubernetes/application/spark-operator': open /opt/my-kubeflow/.cache/manifests/manifests-1.1-branch/stacks/kubernetes/application/spark-operator: no such file or directory
Usage:
  kfctl apply -f ${CONFIG} [flags]

Flags:
      --context string   Optional kubernetes context to use when applying resources. Currently not used by KFDef resources.
  -f, --file string      Static config file to use. Can be either a local path:
                                        export CONFIG=./kfctl_gcp_iap.yaml
                                or a URL:
                                        export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_gcp_iap.v1.0.0.yaml
                                        export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_istio_dex.v1.0.0.yaml
                                        export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_aws.v1.0.0.yaml
                                        export CONFIG=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_k8s_istio.v1.0.0.yaml
                                kfctl apply -V --file=${CONFIG}
  -h, --help             help for apply
  -V, --verbose          verbose output default is false

kfctl exited with error: failed to apply:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: error evaluating kustomization manifest for spark-operator: accumulating resources: accumulating resources from '../../.cache/manifests/manifests-1.1-branch/stacks/kubernetes/application/spark-operator': open /opt/my-kubeflow/.cache/manifests/manifests-1.1-branch/stacks/kubernetes/application/spark-operator
```

**Comment by whalecold** [comment] 2020-09-03 07:23
Hi, I have the same problem, have you solved it ?

**Comment by swiftdiaries** [comment] 2020-09-03 07:36
This is the fix: https://github.com/kubeflow/manifests/pull/1540

**Comment by zhangchunsheng** [comment] 2020-09-03 07:37
> Hi, I have the same problem, have you solved it ?

Yes, I delete the spark-operator in kfctl_k8s_istio.v1.1.0.yaml.

like below

vim kfctl_k8s_istio.v1.1.0.yaml
```
#- kustomizeConfig:
  #    repoRef:
  #      name: manifests
  #      path: stacks/kubernetes/application/spark-operator
  #  name: spark-operator
```

**Comment by swiftdiaries** [comment] 2020-09-03 07:37
This is a duplicate of https://github.com/kubeflow/kubeflow/issues/5246. I'm closing this in favor of that

**Closed** 2020-09-03 07:37 UTC
Labels: area/kfctl, kind/bug

**Comment by whalecold** [comment] 2020-09-03 07:53
> > Hi, I have the same problem, have you solved it ?
> 
> Yes, I delete the spark-operator in kfctl_k8s_istio.v1.1.0.yaml.
> 
> like below
> 
> vim kfctl_k8s_istio.v1.1.0.yaml
> 
> ```
> #- kustomizeConfig:
>   #    repoRef:
>   #      name: manifests
>   #      path: stacks/kubernetes/application/spark-operator
>   #  name: spark-operator
> ```

Thanks !
