### ISSUE TITLE
gcp apply could not update deployment manager - service account does not exist

### ISSUE THREAD

**Issue by JakeTheWise** [kubeflow/kfctl#320] opened 2020-04-23 15:58 UTC
kfctl v1.0.2

I'm trying to spin up kubeflow on GCP from the command line using the instructions [here](https://www.kubeflow.org/docs/gke/deploy/deploy-cli/) but I'm getting this error after running `kfctl apply -V -f https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_gcp_iap.v1.0.2.yaml`

```
Error: failed to apply:  (kubeflow.error): Code 500 with message: coordinator Apply failed for gcp:  (kubeflow.error): Code 400 with message: gcp apply could not update deployment manager Error Set New IamPolicy error: googleapi: Error 400: Service account kubeflow1-0-user@PROJECT.iam.gserviceaccount.com does not exist., badRequest
```

But I thought the service account in question is one of three that kfctl ought to generate automatically.

**Comment by jlewi** [comment] 2020-04-25 15:59
Yes that GSA should be created by kfctl. It should be part of your deployment. Can you check your deployment to see if the GSA was created?

```
gcloud --project=${PROJECT} deployment-manager deployments describe ${KFNAME}
```

**Comment by JakeTheWise** [comment] 2020-04-26 18:30
I ran that command, and everything looks healthy...
`NAME: kubeflow1-0-user TYPE: iam.v1.serviceAccount STATE: COMPLETED`
So I'm not sure what's up.

**Comment by jlewi** [comment] 2020-04-29 02:45
Did you redact your  PROJECT id in the error message?

In the error message it looks like $PROJECT might not have gotten properly set and then substituted. If you look at the error message the service account

```
kubeflow1-0-user@PROJECT.iam.gserviceaccount.com
```

so unless you redacted the error message and changed the name of your actual project that is not the correct service account.

Does the service account exist?

```
gcloud --project=${PROJECT} iam service-accounts list
```

**Comment by JakeTheWise** [comment] 2020-04-29 21:38
I redacted the project id intentionally. In the code, the correct project id is set.

**Comment by jlewi** [comment] 2020-04-30 03:25
Does the service account exist? If you try to update the IAM policy for the service account using gcloud or the cloud console does it work?

**Comment by jlewi** [comment] 2020-05-11 14:45
@JakeTheWise if you need more help please "@" me in your reply so that I will get notified in GitHub thanks.

**Comment by hassanzadeh** [comment] 2020-05-11 15:33
Hey Guys,
I'm having similar issues, when I run gcloud --project=${PROJECT} deployment-manager deployments describe ${KFNAME}, I see service accounts, but when I run gcloud --project=${PROJECT} iam service-accounts list, the list is empty, I guess that is the cause since the error says:
ode 400 with message: gcp apply could not update deployment manager Error Set New IamPolicy error: googleapi: Error 400: Service account xxx-user@project.iam.gserviceaccount.com does not exist., badRequest.

Why the service account list is empty? 
I'm using Kfctl.

**Comment by hassanzadeh** [comment] 2020-05-11 16:10
I did create the accounts manually and gave them all owner/role, although I know that defeats the purpose of aim service accounts. That solved the problem for now, but wasn't kfctl supposed to create the service accounts? And also, how are the service accounts listed by the second account in  my previous post different form the first one (i.e. those listed by deployment manager).

**Comment by jlewi** [comment] 2020-05-12 03:48
When you run

> gcloud --project=${PROJECT} deployment-manager deployments describe ${KFNAME}

You are not listing service accounts. You are listing deployment manager configurations to create the service accounts. Most likely DM manager failed trying to apply them and thats probably why the service accounts weren't created.

Can you please provide the output of 

```
gcloud --project=${PROJECT} deployment-manager deployments describe ${KFNAME}
```

And then do 

```
gcloud --project=${PROJECT} deployment-manager operations describe ${OPNAME}
```

Where OPNAME will be available from the describe command for the deployment.

I suspect DM is failing to create the service accounts possibly because of insufficient permissions.

You could also try looking at the data access audit logs
https://cloud.google.com/logging/docs/audit

If you search for the service account in the audit logs you should be able to see

* Was there a failed attempt to create the service account
* Was the service account created and then deleted?

**Comment by hassanzadeh** [comment] 2020-05-12 18:07
Thanks, I actually removed everything, include service account to start again. Now when I try to do kfctl apply -f xxx.json, It fails with the following issue:
failed to apply:  (kubeflow.error): Code 500 with message: coordinator Apply failed for gcp:  (kubeflow.error): Code 500 with message: gcp apply could not update deployment manager Error could not update storage-kubeflow.yaml; Insert deployment error: Post "https://www.googleapis.com/deploymentmanager/v2/projects/myprj/global/deployments?alt=json&prettyPrint=false": metadata: GCE metadata "instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform" not defined

why is that? The ui as usual, fails too.

**Comment by jlewi** [comment] 2020-05-15 21:37
@hassanzadeh please open a separate issue. It looks like you are running on a GCE vm and it is using the GCE vm service account with insufficient scopes.

**Comment by v-loves-avocados** [comment] 2020-07-06 13:43
I got the same error.

"Error: failed to apply:  (kubeflow.error): Code 500 with message: coordinator Apply failed for gcp:  (kubeflow.error): Code 400 with message: gcp apply could not update deployment manager Error Set Cleared IamPolicy error: %v; googleapi: Error 403: Policy update access denied., forbidden"

I tried this: 
_gcloud --project=${PROJECT} deployment-manager deployments describe ${KF_NAME}_
---
fingerprint: MaCTiT-JfmaDz0qLP7gVhQ==
id: '5123405578347912189'
insertTime: '2020-07-06T06:20:18.758-07:00'
manifest: manifest-1594041618770
name: kubeflow-v2
operation:
  endTime: '2020-07-06T06:23:37.210-07:00'
  name: operation-1594041618728-5a9c5bc7106c5-081a68d4-b49de9d2
  operationType: insert
  progress: 100
  startTime: '2020-07-06T06:20:18.827-07:00'
  status: DONE
  user: myname@myemail.com


NAME                     TYPE                                                               STATE      INTENT
kubeflow-v2              gcp-types/container-v1beta1:projects.locations.clusters            COMPLETED
kubeflow-v2-admin        iam.v1.serviceAccount                                              COMPLETED
kubeflow-v2-gpu-pool-v1  gcp-types/container-v1beta1:projects.locations.clusters.nodePools  COMPLETED
kubeflow-v2-ip           compute.v1.globalAddress                                           COMPLETED
kubeflow-v2-user         iam.v1.serviceAccount                                              COMPLETED
kubeflow-v2-vm           iam.v1.serviceAccount                                              COMPLETED


Any suggestions on what I can do? Thanks

**Comment by PatrickXYS** [comment] 2020-11-25 04:04
Since GCP has migrated out of kfctl and use gcp-blueprint instead, close the issue

/close

**Closed by PatrickXYS** 2020-11-25 04:04 UTC
Labels: kind/bug, platform/gcp, priority/p1
