### ISSUE TITLE
endpoint_is_ready test is failing

### ISSUE THREAD

**Issue by gabrielwen** [kubeflow/kfctl#228] opened 2020-02-12 06:20 UTC
Seems like to be related to Python 2.x deprecation:
https://stackoverflow.com/questions/47142848/python-sslerror-bad-handshake-unexpected-eof

Updating test worker Dockerfile.

**Comment by jlewi** [comment] 2020-02-12 14:38
@gabrielwen I just saw this. It looks like we might have both been working on updating the test worker image.

See https://github.com/kubeflow/testing/pull/606

**Comment by jlewi** [comment] 2020-02-13 13:59
@gabrielwen any update on this?

**Comment by gabrielwen** [comment] 2020-02-14 07:23
still working on the py3 image.

**Comment by gabrielwen** [comment] 2020-02-18 05:58
kubeflow/tf-operator#1133 has to be checked in first so that #227 can be fixed.

**Comment by jlewi** [comment] 2020-02-18 14:59
@gabrielwen could you please explain what the issue is? IIRC there is an issue with the endpoint test requiring python3? 

Do we need to update all the tests to use python3 just to fix the endpoint ready test? Could we just run the endpoint is ready test using the new docker image and let all the remaining tests continue to use the existing python2 based docker image?

**Comment by gabrielwen** [comment] 2020-02-18 17:43
> @gabrielwen could you please explain what the issue is? IIRC there is an issue with the endpoint test requiring python3?
> 
> Do we need to update all the tests to use python3 just to fix the endpoint ready test? Could we just run the endpoint is ready test using the new docker image and let all the remaining tests continue to use the existing python2 based docker image?

you are right we could just use python3 image on endpoint test.  it's just that I thought we'd like to migrate to python3 images.  however, I think changing to python3 on kfctl e2e test is almost completed.

**Comment by jlewi** [comment] 2020-02-18 22:22
@gabrielwen we should definitely migrate to python3; however it would be good to get the endpoint test fixed as soon as possible so that get clear signal about whether KF is working or not.

**Comment by jbottum** [comment] 2020-06-26 20:41
@gabrielwen hey Gabriel - can we please close this issue ?

**Comment by PatrickXYS** [comment] 2020-11-25 04:59
I think this is resolved by https://github.com/kubeflow/kfctl/pull/245

/close

**Closed by PatrickXYS** 2020-11-25 04:59 UTC
Labels: area/1.0.0, area/engprod, area/testing, effort/3-days, kind/bug, priority/p0
